# Generated by Django 5.2.6 on 2025-11-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='user_agent',
            field=models.TextField(blank=True, default='unknown', help_text='Browser/device user agent string', null=True),
        ),
    ]
