# Generated by Django 5.2.6 on 2025-11-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='beds_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='beds_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hero_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='specialties_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
