# Generated by Django 5.2.6 on 2025-11-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
