# Generated by Django 5.2.7 on 2025-11-23 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('psychiatry', 'Psychiatry'), ('urology', 'Urology'), ('oncology', 'Oncology'), ('gynecology', 'Gynecology / Obstetrics'), ('nephrology', 'Nephrology'), ('pulmonology', 'Pulmonology'), ('rheumatology', 'Rheumatology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Otolaryngology)'), ('radiology', 'Radiology'), ('anesthesiology', 'Anesthesiology'), ('emergency', 'Emergency Medicine'), ('family', 'Family Medicine / General Practice')], db_index=True, help_text='Medical specialization (from predefined choices)', max_length=50)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of professional experience')),
                ('qualification', models.CharField(blank=True, help_text='Degrees/certifications (e.g., MBBS, MD)', max_length=255)),
                ('bio', models.TextField(blank=True, help_text='Short professional bio')),
                ('rating', models.FloatField(default=0.0, help_text='Average rating out of 5.0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='Linked account for this doctor', on_delete=django.db.models.deletion.CASCADE, related_name='doctorprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor profile',
                'verbose_name_plural': 'Doctor profiles',
                'ordering': ['-rating', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorprofile')),
            ],
            options={
                'verbose_name': 'Appointment cancellation',
                'verbose_name_plural': 'Appointment cancellations',
                'ordering': ['-cancelled_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, help_text='Doctor that the user has saved/favorited', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='doctors.doctorprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved doctor',
                'verbose_name_plural': 'Saved doctors',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='doctor_timetables/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='doctors.doctorprofile')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['specialization'], name='doctors_doc_special_a5690e_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['-rating'], name='doctors_doc_rating_ef7118_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['experience_years'], name='doctors_doc_experie_32168a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saveddoctor',
            unique_together={('user', 'doctor')},
        ),
    ]
