# Generated by Django 5.2.7 on 2025-11-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('psychiatry', 'Psychiatry'), ('urology', 'Urology'), ('oncology', 'Oncology'), ('gynecology', 'Gynecology / Obstetrics'), ('nephrology', 'Nephrology'), ('pulmonology', 'Pulmonology'), ('rheumatology', 'Rheumatology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Otolaryngology)'), ('radiology', 'Radiology'), ('anesthesiology', 'Anesthesiology'), ('emergency', 'Emergency Medicine'), ('family', 'Family Medicine / General Practice')], max_length=50),
        ),
    ]
