# Generated by Django 5.2.7 on 2025-11-22 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctorprofile_specialization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentcancellation',
            options={'ordering': ['-cancelled_at'], 'verbose_name': 'Appointment cancellation', 'verbose_name_plural': 'Appointment cancellations'},
        ),
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'ordering': ['-rating', 'user__first_name'], 'verbose_name': 'Doctor profile', 'verbose_name_plural': 'Doctor profiles'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prescription', 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Timetable', 'verbose_name_plural': 'Timetables'},
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short professional bio'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of professional experience'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='qualification',
            field=models.CharField(blank=True, help_text='Degrees/certifications (e.g., MBBS, MD)', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Average rating out of 5.0'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('psychiatry', 'Psychiatry'), ('urology', 'Urology'), ('oncology', 'Oncology'), ('gynecology', 'Gynecology / Obstetrics'), ('nephrology', 'Nephrology'), ('pulmonology', 'Pulmonology'), ('rheumatology', 'Rheumatology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Otolaryngology)'), ('radiology', 'Radiology'), ('anesthesiology', 'Anesthesiology'), ('emergency', 'Emergency Medicine'), ('family', 'Family Medicine / General Practice')], db_index=True, help_text='Medical specialization (from predefined choices)', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(help_text='Linked account for this doctor', on_delete=django.db.models.deletion.CASCADE, related_name='doctors_doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['specialization'], name='doctors_doc_special_a5690e_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['-rating'], name='doctors_doc_rating_ef7118_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['experience_years'], name='doctors_doc_experie_32168a_idx'),
        ),
    ]
